### ISSUE TITLE
Pip Install Issues 

### ISSUE THREAD

**Issue by twilkerson1237** [wolfSSL/wolfssl-py#20]
Having issues pip installing WolfSSl. Was this designed to only install on linux machines? 

 Turn off this advice by setting config variable advice.detachedHead to false

    Updating files: 100% (1566/1566), done.
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    'libtoolize' is not recognized as an internal or external command,
    operable program or batch file.
    Traceback (most recent call last):
      File "C:\Users\black\AppData\Local\Temp\pip-install-lxm3h28j\wolfssl\src\wolfssl\_build_wolfssl.py", line 171, in make
        call("./autogen.sh")
      File "C:\Users\black\AppData\Local\Temp\pip-install-lxm3h28j\wolfssl\src\wolfssl\_build_wolfssl.py", line 69, in call
        subprocess.check_call(cmd, shell=True, env=os.environ)
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command './autogen.sh' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\black\AppData\Local\Temp\pip-install-lxm3h28j\wolfssl\setup.py", line 82, in <module>
        setup(
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\site-packages\cffi\setuptools_ext.py", line 144, in run
        base_class.run(self)
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
        _build_ext.run(self)
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\black\AppData\Local\Temp\pip-install-lxm3h28j\wolfssl\setup.py", line 76, in build_extension
        build_wolfssl(wolfssl.__wolfssl_version__)
      File "C:\Users\black\AppData\Local\Temp\pip-install-lxm3h28j\wolfssl\src\wolfssl\_build_wolfssl.py", line 189, in build_wolfssl
        make(make_flags(prefix))
      File "C:\Users\black\AppData\Local\Temp\pip-install-lxm3h28j\wolfssl\src\wolfssl\_build_wolfssl.py", line 173, in make
        call("libtoolize")
      File "C:\Users\black\AppData\Local\Temp\pip-install-lxm3h28j\wolfssl\src\wolfssl\_build_wolfssl.py", line 69, in call
        subprocess.check_call(cmd, shell=True, env=os.environ)
      File "c:\users\black\appdata\local\programs\python\python38-32\lib\subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'libtoolize' returned non-zero exit status 1.
    Calling: 'git clone --depth=1 --branch=v4.1.0-stable https://github.com/wolfssl/wolfssl.git C:\Users\black\AppData\Local\Temp\pip-install-lxm3h28j\wolfssl\lib\wolfssl\src' from working directory C:\Users\black\AppData\Local\Temp\pip-install-lxm3h28j\wolfssl
    Calling: 'git clean -fdX' from working directory C:\Users\black\AppData\Local\Temp\pip-install-lxm3h28j\wolfssl\lib\wolfssl\src
    Calling: './autogen.sh' from working directory C:\Users\black\AppData\Local\Temp\pip-install-lxm3h28j\wolfssl\lib\wolfssl\src
    Calling: 'libtoolize' from working directory C:\Users\black\AppData\Local\Temp\pip-install-lxm3h28j\wolfssl\lib\wolfssl\src
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\black\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\black\\AppData\\Local\\Temp\\pip-install-lxm3h28j\\wolfssl\\setup.py'"'"'; __file__='"'"'C:\\Users\\black\\AppData\\Local\\Temp\\pip-install-lxm3h28j\\wolfssl\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\black\AppData\Local\Temp\pip-record-khfdl5ri\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by dgarske** [comment]
Hi @twilkerson1237 , 

Thank you for your report. We have had some issues getting the Python wrappers to work with Windows.

We have made some efforts in the wolfcrypt-py for building on Windows here: https://github.com/wolfSSL/wolfcrypt-py/pull/13 
Hopefully that can provide some useful tips.

If you are interested in contributing please feel free to put up a PR.

Thanks, David Garske, wolfSSL

**Comment by dgarske** [comment]
Hi @twilkerson1237 ,

Following up on this old topic. It is no longer required to use wolfcrypt-py.

In wolfBoot we now have C based tools. You can use `make keytools` or build the Visual Studio project here (https://github.com/wolfSSL/wolfBoot/tree/master/tools/keytools).

Thanks,
David Garske, wolfSSL
